- .cargo/config.toml
- trainer/src/arch/nnue.rs
- trainer/src/arch/quantise.rs
- trainer/src/main.rs
- trainer/src/trainer.rs
Avoid stack overflows with large nets.
> Support Large Nets

- README.md
> Document standard Ataxx notation

- bullet-utils/src/count_buckets.rs
- bullet-utils/src/main.rs
Needs a file containing a bucketing scheme such as this:
```
0, 0, 1, 1, 1, 1, 0, 0,
2, 2, 3, 3, 3, 3, 2, 2,
4, 4, 4, 4, 4, 4, 4, 4,
4, 4, 4, 4, 4, 4, 4, 4,
4, 4, 4, 4, 4, 4, 4, 4,
4, 4, 4, 4, 4, 4, 4, 4,
4, 4, 4, 4, 4, 4, 4, 4,
4, 4, 4, 4, 4, 4, 4, 4,
```
Shows the bucket layout from white's perspective, and gives output like the following:
```
./bullet-utils.exe bucket-count --bucket-file bucket_file.txt data_1.bin data_2.bin
Bucket layout:
+-------------+------------+------------+------------+------------+------------+------------+------------+
|           4 |          4 |          4 |          4 |          4 |          4 |          4 |          4 |
+-------------+------------+------------+------------+------------+------------+------------+------------+
|           4 |          4 | …
```
> Utility to count king square distributions

- build.rs
- src/backend/hip/bindings.rs
- src/backend/hip/ops.rs
- src/backend/kernels/hip/pairwise_mul.hip
```
running 11 tests
test tensor::tests::affine ... ok
test tensor::tests::mse ... ok
test tensor::tests::reduce_add_mul_vector_vectort ... ok
test tensor::tests::select ... ok
test tensor::tests::tensor_activate ... ok
test tensor::tests::tensor_lt ... ok
test tensor::tests::tensor_pairwise_mul ... ok
test tensor::tests::tensor_pairwise_mul_perspective ... ok
test tensor::tests::tensor_reduce_add ... ok
test tensor::tests::tensor_sparse_affine ... ok
test tensor::tests::tensor_splat_add ... ok
test result: ok. 11 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.65s
```
> HIP Pairwise Multiplication Support

- examples/akimbo-main.rs
- examples/ataxx.rs
- examples/morelayers.rs
- examples/simple.rs
- examples/testnet.rs
- src/lib.rs
- src/loader/direct_sequential.rs
- src/loader/mod.rs
- src/trainer/run.rs
Add support for user-defined custom data loaders e.g. to load from binpacks.
> Support Custom Data Loaders

- src/trainer/default/quant.rs
> Fix error on old rust versions

- README.md
- docs/0-contents.md
- docs/4-saved-networks.md
> Better Documentation for Network Output Format

- src/trainer/default/quant.rs
> Support `i8` Quantisation

- utils/src/shuffle.rs
Reading a 18GB file took ~42s before, and with a theoretical file read speed of 500MB/s it should more be like 36s. 
Switching to vectored read, results in read time of ~37s. Resulting in roughly 10% speedup.
> Use vectored read instead of exact read

- src/trainer/default.rs
- src/trainer/default/inputs.rs
- src/trainer/default/loader.rs
- src/trainer/default/outputs.rs
Every `BulletFormat` type automatically impls `LoadableDataType` so no breaking changes.
Closes #213
> Add `LoadableDataType` to replace `BulletFormat` requirement

- src/trainer/default.rs
> Fix unsound `CanBeDirectlySequentiallyLoaded` impl

- examples/advanced.rs
- src/trainer/default.rs
- src/trainer/default/builder.rs
- src/trainer/default/inputs.rs
- src/trainer/default/inputs/legacy.rs
- src/trainer/default/loader.rs
> Add `SparseInputType` to replace `InputType`

- src/trainer/default/builder.rs
Closes #221 
Closes #222 
Closes #215
> Improve `TrainerBuilder::build`

- crates/bullet_lib/src/trainer/schedule/lr.rs
- crates/bullet_lib/src/trainer/schedule/wdl.rs
Previously, warmup batches didn't do anything since superbatch starts at 1
> Fix warmup batches

- crates/bullet_utils/src/validate.rs
> Report stats in validation utility

- crates/bullet_core/src/device/error.rs
- crates/bullet_core/src/graph/builder.rs
- crates/bullet_core/src/graph/operation.rs
- crates/bullet_core/src/graph/operation/matmul.rs
- crates/bullet_core/src/graph/tests/activate.rs
- crates/bullet_core/src/graph/tests/affine.rs
- crates/bullet_core/src/graph/tests/concat.rs
- crates/bullet_core/src/graph/tests/sparse_affine.rs
- crates/bullet_core/src/optimiser.rs
- crates/bullet_core/src/optimiser/utils.rs
- crates/bullet_core/src/tensor.rs
- crates/bullet_core/src/tensor/matrix.rs
- crates/bullet_core/src/tensor/sparse.rs
- crates/bullet_hip_backend/src/sparse.rs
- crates/bullet_lib/src/frontend.rs
- crates/bullet_lib/src/trainer.rs
- crates/bullet_lib/src/trainer/default.rs
- crates/bullet_lib/src/trainer/default/builder.rs
- examples/advanced.rs
> Separate sparse/dense when building graph

- crates/bullet_lib/src/trainer.rs
> Fix validation batches when batches per superbatch < 32

- crates/bullet_utils/src/count_buckets.rs
- crates/bullet_utils/src/validate.rs
> Fix counter overflow in `validate` utility

- crates/bullet_lib/src/trainer/schedule/lr.rs
- crates/bullet_lib/src/trainer/schedule/wdl.rs
I've been wanting to play around with a [Smith et al](https://arxiv.org/abs/1708.07120) style "one cycle learning rate", where the LR increases, and then decreases. I thought about implementing this as a scheduler by itself, and then realised a more general solution is to be able to sequence (I could call it `chain` like Rust's `Iterator` trait does) two schedulers together.
> Add combinator to sequence two schedulers

- crates/bullet_core/src/graph/builder.rs
- crates/bullet_core/src/graph/ir.rs
- crates/bullet_core/src/graph/ir/operation.rs
- crates/bullet_core/src/graph/ir/operation/binary.rs
- crates/bullet_core/src/graph/ir/operation/sparse.rs
- crates/bullet_core/src/graph/ir/operation/unary.rs
> Add dumping `GraphIR` to graphviz for visualisation
